plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tuhin.youtubetv'
    compileSdk 34

    defaultConfig {
        applicationId "com.tuhin.youtubetv"
        minSdk 17
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('E:/keys/android_tv_app_youtube.jks')
            storePassword 'tuhin2008'
            keyAlias 'key0'
            keyPassword 'tuhin2008'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
