plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tuhin.youtubetv'
    compileSdk 34

    defaultConfig {
        applicationId "com.tuhin.youtubetv"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('E:/keys/android_tv_app_youtube.jks')
            storePassword 'tuhin2008'
            keyAlias 'key0'
            keyPassword 'tuhin2008'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.12.0'
            force 'androidx.core:core-ktx:1.12.0'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    
    // GeckoView (Version 115 is the last to support API 21+)
    implementation "org.mozilla.geckoview:geckoview:115.0.20230726201356"
}
